# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: pwd&&ls&&docker build . -t capture && docker run capture
    - name: Commit
      run: |
        git config user.email 'update-capture@example.com'
        git config user.name 'update-capture'
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git checkout -b update-capture
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin update-capture)
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
